/**
 * Seed data ported from frontend/src/mocks/* — keep the two in sync
 * until the frontend switches fully to the API.
 */

const images = (seed: string, count = 4) =>
  Array.from({ length: count }, (_, i) => `https://picsum.photos/seed/${seed}-${i + 1}/800/800`);

const base = { variants: [], deliveryDays: 2, returnDays: 7, isActive: true, salesCount: 0 };

export const seedProducts = [
  {
    ...base,
    slug: 'santoor-with-activities-class-4-ncert',
    title: 'Santoor With Activities Class 4 NCERT',
    brand: 'PPD',
    category: 'books',
    description:
      'NCERT-aligned Santoor textbook with in-book activities for Class 4. Colourful illustrations, practice exercises and chapter-wise revision — trusted by schools across India.',
    highlights: ['NCERT syllabus aligned', 'Includes chapter activities', 'Full-colour illustrations', 'Class 4 · English medium'],
    images: images('santoor-ncert'),
    price: 299,
    mrp: 400,
    rating: 4.8,
    ratingCount: 49,
    reviewCount: 21,
    stock: 120,
    tags: ['featured', 'bestseller'],
  },
  {
    ...base,
    slug: 'single-line-small-notebooks-76-pages-set-of-6',
    title: 'Single Line Small Notebooks 76 Pages (Set of 6)',
    brand: 'Classmate',
    category: 'stationery',
    description:
      'Set of 6 single-line small notebooks, 76 pages each. Smooth 58 GSM paper for neat handwriting, sturdy covers that survive the school bag.',
    highlights: ['Set of 6 notebooks', '76 pages each', 'Smooth 58 GSM paper', 'Durable laminated covers'],
    images: images('notebook-set'),
    price: 140,
    mrp: 180,
    rating: 4.5,
    ratingCount: 10,
    reviewCount: 6,
    stock: 200,
    tags: ['featured', 'deal'],
  },
  {
    ...base,
    slug: 'doms-hexel-pen-blue-20-pcs',
    title: 'DOMS Hexel Pen Blue 20 Pcs',
    brand: 'DOMS',
    category: 'stationery',
    description:
      'Classroom pack of 20 DOMS Hexel ball pens in blue. Hexagonal grip for comfortable writing, low-viscosity ink for smooth, smudge-free notes.',
    highlights: ['Pack of 20 pens', 'Hexagonal comfort grip', 'Smudge-free blue ink', '0.7mm tip'],
    images: images('doms-pens'),
    price: 311,
    mrp: 400,
    rating: 4.6,
    ratingCount: 70,
    reviewCount: 32,
    stock: 150,
    tags: ['featured', 'deal'],
  },
  {
    ...base,
    slug: 'classmate-asteroid-geometry-box',
    title: 'Classmate Asteroid Geometry Box',
    brand: 'Classmate',
    category: 'stationery',
    description:
      'Classmate Asteroid geometry box with precision instruments in a compact metal case — compass, divider, set squares, protractor and scale.',
    highlights: ['Full instrument set', 'Rust-resistant metal case', 'Accurate markings', 'Ideal for Grades 4–10'],
    images: images('classmate-geometry'),
    price: 311,
    mrp: 400,
    rating: 4.1,
    ratingCount: 65,
    reviewCount: 28,
    stock: 85,
    tags: ['deal'],
  },
  {
    ...base,
    slug: 'supplementary-sheet-2-pages',
    title: 'Supplementary Sheet 2 Pages',
    brand: 'PPD',
    category: 'books',
    description:
      'Official 2-page supplementary answer sheet, exam-standard ruling and quality paper. Sold per sheet — stock up for the exam season.',
    highlights: ['Exam-standard ruling', '2 pages per sheet', 'Smooth ink-friendly paper', 'Sold per sheet'],
    images: images('supplementary-sheet'),
    price: 3.2,
    mrp: 4,
    rating: 5.0,
    ratingCount: 13,
    reviewCount: 4,
    stock: 5000,
    tags: ['bestseller'],
  },
  {
    ...base,
    slug: 'state-board-answer-sheet',
    title: 'STATE BOARD ANSWER SHEET',
    brand: 'PPD',
    category: 'books',
    description:
      'State board pattern answer sheet for exam practice at home and school. Matches official layout so students get comfortable before the real exam.',
    highlights: ['Official state board pattern', 'Exam-quality paper', 'Great for mock tests', 'Bulk-friendly pricing'],
    images: images('state-board-sheet'),
    price: 13.5,
    mrp: 400,
    rating: 4.5,
    ratingCount: 40,
    reviewCount: 12,
    stock: 3000,
    tags: [],
  },
  {
    ...base,
    slug: 'camlin-scholar-pro-geometry-box',
    title: 'Camlin Scholar Pro Geometry Box',
    brand: 'Camlin',
    category: 'stationery',
    description:
      '12-Piece Set | Premium Geometry Box Kit for School kids | Ideal for Learning and Precision | Pack of 1',
    highlights: ['12-piece premium kit', 'Self-centering compass', 'Shatter-resistant protractor', 'Compact flip-top case'],
    images: images('camlin-geometry'),
    price: 300,
    mrp: 350,
    rating: 4.8,
    ratingCount: 49,
    reviewCount: 18,
    stock: 60,
    tags: ['trending', 'bestseller'],
    bought: '1,680 Brought this week',
  },
  {
    ...base,
    slug: 'a5-classic-spiral-bound-notebooks',
    title: 'A5 Classic Spiral Bound Notebooks',
    brand: 'Classmate',
    category: 'stationery',
    description:
      'A5 spiral-bound notebooks with lay-flat binding, 160 ruled pages and thick board backs — the everyday classroom favourite.',
    highlights: ['Lay-flat spiral binding', '160 ruled pages', 'Thick board back', 'A5 carry-friendly size'],
    images: images('a5-spiral'),
    price: 249,
    mrp: 320,
    rating: 4.8,
    ratingCount: 49,
    reviewCount: 20,
    stock: 140,
    tags: ['trending'],
    bought: '1.5K+ bought',
  },
  {
    ...base,
    slug: 'shuttle-art-6-pcs-highlighters',
    title: 'Shuttle Art 6 Pcs Highlighters',
    brand: 'Shuttle Art',
    category: 'stationery',
    description:
      'Six chisel-tip highlighters in soft pastel shades. Quick-dry, bleed-resistant ink that keeps textbooks clean and notes vivid.',
    highlights: ['6 pastel shades', 'Chisel tip — fine & broad', 'Quick-dry, no smudging', 'Bleed-resistant ink'],
    images: images('highlighters'),
    price: 199,
    mrp: 260,
    rating: 4.8,
    ratingCount: 49,
    reviewCount: 17,
    stock: 90,
    tags: ['trending'],
    bought: '1.3K+ bought',
  },
  {
    ...base,
    slug: 'dual-tips-24-colours-markers',
    title: 'Dual Tips 24 Colours Markers',
    brand: 'DOMS',
    category: 'stationery',
    description:
      '24 vibrant dual-tip markers — brush tip for art, fine tip for outlines. Water-based, non-toxic and safe for young artists.',
    highlights: ['24 colours', 'Brush + fine dual tips', 'Non-toxic, water-based', 'Storage case included'],
    images: images('dual-markers'),
    price: 449,
    mrp: 599,
    rating: 4.8,
    ratingCount: 49,
    reviewCount: 23,
    stock: 75,
    tags: ['trending'],
    bought: '9K+ bought',
  },
  {
    ...base,
    slug: 'ppd-school-backpack',
    title: 'PPD Ergo School Backpack 25L',
    brand: 'PPD',
    category: 'bags',
    description:
      'Ergonomic 25L school backpack with padded straps, ventilated back panel, laptop/tablet sleeve and a rain-ready water-repellent shell.',
    highlights: ['Ergonomic padded straps', '25L, 3 compartments', 'Water-repellent shell', 'Reflective safety strip'],
    images: images('school-backpack'),
    price: 899,
    mrp: 1299,
    rating: 4.4,
    ratingCount: 88,
    reviewCount: 35,
    stock: 45,
    tags: ['featured'],
  },
  {
    ...base,
    slug: 'kids-auto-umbrella',
    title: 'Kids Auto-Open Umbrella',
    brand: 'RainPals',
    category: 'for-kids',
    description:
      'Lightweight auto-open umbrella sized for small hands, with pinch-proof runners and a rounded safety tip. Bright panels keep kids visible.',
    highlights: ['One-touch auto open', 'Pinch-proof design', 'High-visibility colours', 'Rust-proof frame'],
    images: images('kids-umbrella'),
    price: 249,
    mrp: 349,
    rating: 4.3,
    ratingCount: 41,
    reviewCount: 15,
    stock: 110,
    tags: [],
  },
  {
    ...base,
    slug: 'school-raincoat',
    title: 'School Raincoat with Bag Cover',
    brand: 'RainPals',
    category: 'for-kids',
    description:
      'PVC-free school raincoat with an extended back flap that covers the school bag too. Reflective piping and a snug hood for windy days.',
    highlights: ['Built-in bag cover flap', 'PVC-free fabric', 'Reflective piping', 'Sizes for ages 5–14'],
    images: images('school-raincoat'),
    price: 399,
    mrp: 549,
    rating: 4.2,
    ratingCount: 27,
    reviewCount: 9,
    stock: 95,
    tags: [],
  },
  {
    ...base,
    slug: 'yoga-mat-kids',
    title: 'Yoga Mat',
    brand: 'PPD',
    category: 'for-kids',
    description: 'Comfortable mats for yoga, stretching and daily fitness.',
    highlights: ['6mm cushioning', 'Non-slip texture', 'Easy-clean surface', 'Carry strap included'],
    images: images('yoga-mat-ppd'),
    price: 99,
    mrp: 149,
    rating: 4.5,
    ratingCount: 33,
    reviewCount: 11,
    stock: 130,
    tags: [],
  },
  {
    ...base,
    slug: 'sports-towels',
    title: 'Towels',
    brand: 'PPD',
    category: 'for-kids',
    description: 'Soft, absorbent towels to keep you fresh during every session.',
    highlights: ['Quick-dry microfibre', 'Super absorbent', 'Compact fold', 'Machine washable'],
    images: images('sports-towel'),
    price: 49,
    mrp: 79,
    rating: 4.4,
    ratingCount: 19,
    reviewCount: 7,
    stock: 160,
    tags: [],
  },
  {
    ...base,
    slug: 'water-bottle-steel',
    title: 'Steel Sipper Water Bottle 750ml',
    brand: 'Milton',
    category: 'for-kids',
    description:
      'Leak-proof 750ml steel sipper that keeps water cool through the school day. One-hand flip cap and a carry loop for the bag hook.',
    highlights: ['750ml capacity', 'Leak-proof flip cap', 'Food-grade steel', 'Keeps water cool'],
    images: images('water-bottle'),
    price: 349,
    mrp: 499,
    rating: 4.6,
    ratingCount: 58,
    reviewCount: 22,
    stock: 105,
    tags: [],
  },
];

export const seedCategories = [
  { slug: 'all', name: 'All', icon: 'apps', color: '#8A6FDF', description: '', image: '', sortOrder: 0, isActive: true },
  { slug: 'books', name: 'Books', icon: 'menu_book', color: '#E4573D', description: 'Books, learning resources in one place.', image: 'https://picsum.photos/seed/books/400/400', sortOrder: 1, isActive: true },
  { slug: 'stationery', name: 'Stationery', icon: 'edit', color: '#2F9E63', description: 'Pens, pencils, markers and everyday writing tools.', image: 'https://picsum.photos/seed/stationery/400/400', sortOrder: 2, isActive: true },
  { slug: 'bags', name: 'Bags', icon: 'backpack', color: '#3E7BFA', description: 'Backpacks, bags and carrying solutions.', image: 'https://picsum.photos/seed/bags/400/400', sortOrder: 3, isActive: true },
  { slug: 'for-kids', name: 'For Kids', icon: 'toys', color: '#F5A623', description: 'Fun, educational and creative products for kids.', image: 'https://picsum.photos/seed/kids/400/400', sortOrder: 4, isActive: true },
];

export const seedBrands = [
  { name: 'PPD' },
  { name: 'Classmate' },
  { name: 'DOMS' },
  { name: 'Camlin' },
  { name: 'Shuttle Art' },
  { name: 'RainPals' },
  { name: 'Milton' },
];

export const seedBanners = [
  {
    title: 'Smart\nSchool\nShopping',
    subtitle: 'Find Everything\nFor Your School In One Place',
    cta: 'Explore Now',
    href: '/products',
    image: '/components/carousel.png',
    tone: 'bg-grad-hero',
    sortOrder: 0,
    isActive: true,
  },
  {
    title: 'Back to\nSchool Sale',
    subtitle: 'Up to 30% off\nnotebooks, kits & more',
    cta: 'Shop Deals',
    href: '/products?tag=deal',
    image: '/components/carousel.png',
    tone: 'bg-grad-hero',
    sortOrder: 1,
    isActive: true,
  },
  {
    title: 'Monsoon\nReady Kids',
    subtitle: 'Umbrellas, raincoats\nand bag covers',
    cta: 'Stay Dry',
    href: '/products/all?category=for-kids',
    image: '/components/carousel.png',
    tone: 'bg-grad-hero',
    sortOrder: 2,
    isActive: true,
  },
  {
    title: 'From the\nHouse of PPD',
    subtitle: '100 years of\neducational excellence',
    cta: 'Discover PPD',
    href: '/products/all?category=books',
    image: '/components/carousel.png',
    tone: 'bg-grad-hero',
    sortOrder: 3,
    isActive: true,
  },
  {
    title: 'Build Your Bundle & Save More!',
    subtitle: 'Pick your favourite stationery items and get up to 30% OFF',
    cta: 'Build Bundle',
    href: '/products/all?category=stationery',
    image: '/components/carousel2.png',
    tone: 'bg-grad-hero',
    sortOrder: 0,
    isActive: true,
    placement: 'bundle',
  },
];

const img = (seed: string, w = 300, h = 300) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

/** Product references use SLUGS — the product detail endpoint accepts them. */
export const seedHomeContent = {
  houseCards: [
    { title: 'School Books', image: img('ppd-school-books', 160, 200), href: '/products/all?category=books' },
    { title: 'General Knowledge', image: img('ppd-gk', 160, 200), href: '/products/all?category=books' },
    { title: 'Yoga', image: img('ppd-yoga-book', 160, 200), href: '/products/all?category=books' },
    { title: 'Cyber World', image: img('ppd-cyber', 160, 200), href: '/products/all?category=books' },
  ],
  yogaTiles: [
    { label: 'Mats', image: '/images/image%2023.png', href: '/product/yoga-mat-kids' },
    { label: 'Headbands', image: '/images/image%2024.png', href: '/products/all?category=for-kids' },
    { label: 'Towels', image: '/images/image%2026.png', href: '/product/sports-towels' },
    { label: 'Bottles', image: '/images/image%2025.png', href: '/product/water-bottle-steel' },
  ],
  yogaPromos: [
    {
      name: 'Yoga Mat',
      desc: 'Comfortable mats for yoga, stretching and daily fitness.',
      price: 99,
      image: '/images/image1.png',
      productId: 'yoga-mat-kids',
    },
    {
      name: 'Towels',
      desc: 'Soft, absorbent towels to keep you fresh during every session.',
      price: 49,
      image: '/images/image_towel.png',
      productId: 'sports-towels',
    },
  ],
  packages: [
    { name: 'Complete Writing Kit', blurb: 'Perfect for a fresh start to the year', price: 311, image: '/images/packages/writing-kit.png', href: '/products/all?category=stationery' },
    { name: 'Art Kits', blurb: 'Perfect for a fresh start to the year', price: 311, image: '/images/packages/art-kit.png', href: '/products/all?category=stationery' },
    { name: 'Craft Kits', blurb: 'Perfect for a fresh start to the year', price: 311, image: '/images/packages/craft-kit.png', href: '/products/all?category=stationery' },
    { name: 'Exam Kits', blurb: 'Perfect for a fresh start to the year', price: 311, image: '/images/packages/exam-kit.png', href: '/products/all?category=stationery' },
  ],
  categoryChips: ['Textbooks', 'Reference Books', 'Story Books', 'Workbooks'],
  popularSearches: ['Doms Geometry Box', 'Camlin Box', 'Geometry Box'],
};

export const seedCoupons = [
  {
    code: 'WELCOME10',
    title: '10% off your first order',
    description: 'Get 10% off up to ₹300 on a minimum order of ₹999.',
    kind: 'percent',
    value: 10,
    minOrder: 999,
    maxDiscount: 300,
    expiresAt: new Date('2026-12-31T23:59:59Z'),
    isActive: true,
  },
  {
    code: 'FLAT150',
    title: 'Flat ₹150 off',
    description: 'Flat ₹150 off on orders above ₹1,499.',
    kind: 'flat',
    value: 150,
    minOrder: 1499,
    maxDiscount: null,
    expiresAt: new Date('2026-09-30T23:59:59Z'),
    isActive: true,
  },
  {
    code: 'MEGA25',
    title: '25% off school essentials',
    description: '25% off up to ₹1,000 on orders above ₹2,999.',
    kind: 'percent',
    value: 25,
    minOrder: 2999,
    maxDiscount: 1000,
    expiresAt: new Date('2026-08-15T23:59:59Z'),
    isActive: true,
  },
];
